post http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2MzAyYTQ0M2ZlNmEyZDFkNTQ3OWU3MTMiLCJpYXQiOjE2NjE4MDkyMjV9.IjMQyFnRWVt4gHJu6sOX6iGtiUmqESGSUL45APDsy7M

{
  "title": "Single Page Apps use token authentication",
  "author": "Dan Abramov",
  "url": "https://danabramov.com/articles/single-page-apps-use-token-authentication.html",
  "likes": 8
}

//"userId": "6302a443fe6a2d1d5479e713" Matti Luukkainen
//"userId": "63095929fbfca91118284a7a" Arto Hellas