POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Aalto yliopiston Vappujuhlat",
  "author": "Matti Mattinen", 
  "url": "https://www.aalto.fi/fi/tietotekniikan-laitos",
  "likes": 5
}